# This Travis-CI file is for testing the functionality of my Makefile.
# It is NOT for testing MOM6.

# This is a not a c-language project but it does use "make"
language: c

cache:
  directories:
    - build/gnu
    - src

# Prerequisites for using the Makefile to build MOM6
install:
 - sudo apt-get install tcsh pkg-config
 - sudo apt-get install gfortran
 - sudo apt-get install netcdf-bin libnetcdf-dev
 - sudo apt-get install openmpi-bin libopenmpi-dev

# Test critical targets in the Makefile
script:
 - find . -type d
 - make clone
 - make dev_tags
 - find . -type d
 # Make sure there is something to copy from src/
 - touch src/noop
 # Copy cached src code (preserving dates)
 - cp -rp src/* MOM6-examples/src/
 # Pull latest source code
 - make dev_pull
 - make SITE=linux FC=mpif77 CC=mpicc LD=mpif77 BUILD_DIR=build REL_PATH=../../../.. build/gnu/shared/repro/libfms.a
 - make SITE=linux FC=mpif77 CC=mpicc LD=mpif77 MOM6-examples/build/gnu/ocean_only/repro/MOM6
 # Cache source code
 - cp -rp MOM6-examples/src/* src/
 - find . -type d
 - make SITE=linux MPIRUN=mpirun NPES=2 MOM6-examples/ocean_only/double_gyre/ocean.stats.gnu
#- make stats.all.md5sums
#- make test.all.md5sums
