# This Travis-CI file is for testing the functionality of my Makefile.
# It is NOT for testing MOM6.

# This is a not a c-language project but it does use "make"
language: c

cache:
  directories:
    - my_cache

# Prerequisites for using the Makefile to build MOM6
install:
 - sudo apt-get install tcsh pkg-config
 - sudo apt-get install gfortran
 - sudo apt-get install netcdf-bin libnetcdf-dev
 - sudo apt-get install openmpi-bin libopenmpi-dev

# Test critical targets in the Makefile
script:
 - ls -Rl
 - make clone
 - make dev_tags
 - ls -l
 # Extract cached src code (preserving dates)
 - tar zvxf my_cache/src.tgz
 # Pull latest source code
 - make dev_pull
 # Cache source code
 - tar zcvf my_cache/src.tgz MOM6-examples/src/*
 # Extract cached build
 - tar zvxf my_cache/build.tgz
 - make SITE=linux FC=mpif77 CC=mpicc LD=mpif77 BUILD_DIR=build REL_PATH=../../../.. build/gnu/shared/repro/libfms.a
 - make SITE=linux FC=mpif77 CC=mpicc LD=mpif77 MOM6-examples/build/gnu/ocean_only/repro/MOM6
 # Cache build
 - tar zcvf my_cache/build.tgz build
 - ls -l my_cache
 - make SITE=linux MPIRUN=mpirun NPES=2 MOM6-examples/ocean_only/double_gyre/ocean.stats.gnu
#- make stats.all.md5sums
#- make test.all.md5sums
